services:
  - type: web
    plan: free
    name: FileStreamBot-1v2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py 
    repo: https://github.com/searchingshiv/FileStreamBot-1v2.git   
    branch: main
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: FORCE_SUB 
        sync: false
      - key: DB_NAME 
        sync: false
      - key: DB_URL 
        sync: false 
      - key: START_PIC 
        sync: false
      - key: ADMIN 
        sync: false    
    autoDeploy: false 
